---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-user-secret
  namespace: votingapp
spec:
  encryptedData:
    APP_PASSWORD: AgArHza5h29CiThkguSqrvVasrTz/sIZujAO1X4c2zf2BAM6Knsig7eyH4cheYevvE/pIjj9SbeLhtWlnCpXl92WVbLwBDVlWG+zCmhC8Y/pRiorAy2Wml1tkItiXkIvKBDABFQXvR452mFaJLSaiQSomhSLDahCYhvZ59GFWcHpVGg+9jlT/a7vaqYNcIugpBJ8iV8Zg87nDDuuvZdvyw0QG+YgzFmdumyPBO8ra1ldrfd6n+t59yCXzFzcNiVYidKB1ek0MDS+NL20OU1zeQq8uGKvT5O9qbjvF6D+OCQzv3qddDEHh282Q3QsttYg24DL558PoHueEFppHpY75mCz1njTu9GUWMaB/0Sf6bZh+RreHJINlWTQvDDAo+qyf0Zy2thSyZGdOQGuKx6M+KKMXD3qTTnm21+qcNYebNKfulgA3crBzTcp2L9HyOdP17tkXFq6ZgE0krfdhoaYnUHcP89qmW+3jj9wnLBqyo0SYj/hDq3BjAop7rfQl8FoJ0fyOnAoPkLsdbis/12rYpWFikXcMAKImgW+1GnqhBBlnLWVilBYjvrqEJl96JVyedOjAR09dzZWkWY2nzbTT5BztLxbFS6tCIKuiHXmCd3y9qrl1yagijM42i2NaWz1H+1TELUIR1ouJUoKt8eCLMGtyI+9XGpAxO7CcimYjXUpHf1zfUa+0JguwKShupfonC2zwwhqpQ4iRg==
    APP_USER: AgBnToN8SLSTVraSTJmqBnSDbjwaid8ODm8dMsXIt0zCb96rUKCCcFpM5lD5ifj8uJb4JnXlyEDdhLwFmlFpGOCLZj8QKc+CsCNEWjn0czOGA7/AolVTTSE5WSevkjJbdvCMIBDUdWAsZUdPNfV/1TC+Afz58hVkKvwD9W07RSEw+k6xcHQM/Me+qIN53TlLTFQHEhXinI9P/ulNpwRGr98fAMEQIfQykWy0WLQEG3T0ehr+utawq8b9j4aAdbL0AlBnPMvvZj7Nb3e5+tTtfk5UJrlP/KAqPUPlIy3FutTM7RV9yrO/sKNP3pFat8zI9hR9gRVvDxbxwwj4XDGM77ueno0rMnlKyNnVFtwOcg2XJr7ScSays1l9WNJMa5VkbPy86yylaBpGVJM6bz8gt8qcR5tRU/Xw4gW7ABongbIMAAPeZchKpLn3Zyf1IxZ/VzV1E/ijMbxqFATaWDTxFJLH8hZyTqFzmDjkuUlbAl7im8c++LfFCkChsz6Gs2RqwEfu/zi6WkrnbwcVE1ukFUTWGt4pYl9cKAC1hOD8bM/jGrNl+U0lqIj3ymAcgwfyrZN1X1bfjzS56bsI1RM6UncOGPYev9u7DWcwpYJ/H1vBH5xtsVWx99hNhn8Tky+aRnQF2XYC2+uGAFpjffcJMp4AydKflo3+Ydo8Ym5ju0l+0E4uSqZ9PxwBFDYLjdgxcnhxbtQxVOFbhQ==
  template:
    metadata:
      creationTimestamp: null
      name: app-user-secret
      namespace: votingapp
