apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      type: frontend
      ha: 'true'
  template:
    metadata:
      labels:
        app: nginx
        type: frontend
        ha: 'true'
    spec:
      containers:
      - name: nginxrs
        image: nginx  