apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    kubernetes.io/change-cause: "Initial creation of redis service"
  namespace: votingapp
  labels:
    app: voting-app-redis
spec:
  selector:
    app: voting-app-redis
  ports:
    - name: redis
      port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  annotations:
    kubernetes.io/change-cause: "Initial creation of redis stateful set"
  namespace: votingapp
  labels:
    app: voting-app-redis
spec:
  serviceName: redis
  replicas: 2
  selector:
    matchLabels:
      app: voting-app-redis
  template:
    metadata:
      labels:
        app: voting-app-redis
    spec:        
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          args: ["redis-server"]
      volumes:
        - name: redis-data
          emptyDir: {}